apiVersion: v1
kind: ConfigMap
metadata:
  name: object-detection-config
  namespace: object-detection
  labels:
    app: object-detection-api
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  MAX_UPLOAD_SIZE: "50MB"
  MAX_WORKERS: "4"
  
  # API Configuration
  API_VERSION: "v1"
  API_TITLE: "Object Detection API"
  API_DESCRIPTION: "Advanced Object Detection API with YOLO, R-CNN, SSD, and EfficientDet models"
  
  # Model Configuration
  DEFAULT_MODEL: "yolo"
  CONFIDENCE_THRESHOLD: "0.5"
  NMS_THRESHOLD: "0.4"
  
  # Performance Configuration
  BATCH_SIZE: "8"
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30"
  
  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: object-detection
  labels:
    app: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream api {
            server object-detection-api:8000;
        }
        
        server {
            listen 80;
            server_name _;
            
            # API endpoints
            location /api/ {
                proxy_pass http://api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Handle large file uploads
                client_max_body_size 50M;
                proxy_read_timeout 300s;
                proxy_connect_timeout 75s;
            }
            
            # Documentation
            location /docs/ {
                alias /usr/share/nginx/html/docs/;
                index index.html;
            }
            
            # Health check
            location /health {
                proxy_pass http://api/health;
            }
            
            # Static files
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }