apiVersion: v1
kind: PersistentVolume
metadata:
  name: object-detection-models-pv
  labels:
    app: object-detection-api
    type: models
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/object-detection/models

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-detection-models-pvc
  namespace: object-detection
  labels:
    app: object-detection-api
    type: models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: object-detection-uploads-pv
  labels:
    app: object-detection-api
    type: uploads
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/object-detection/uploads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-detection-uploads-pvc
  namespace: object-detection
  labels:
    app: object-detection-api
    type: uploads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  labels:
    app: postgres
    type: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: object-detection
  labels:
    app: postgres
    type: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd